global:
  db_type: oracle
  instance_config_file: /qhl/redis/tools/etc/monitor.conf
  interval: 10

item_detail:
  item_detail_01:
    name: name01 # 监控名称
    enabled: y #是否可用
    type: sql # 监控类型
    cmd: select count(*) from v$session # SQL or 命令

  item_detail_02:
    name: name02
    enabled: y
    type: sql
    cmd: select value from v$pgastat where name in ('cache hit percentage')

  item_detail_03:
    name: name03
    enabled: y
    type: shell
    cmd: sudo /opt/cgtools/bin/cginfo -t performance -s memory|grep asdf12qw|awk '{print $8}'|tr -d '%'
